### ISSUE TITLE
Roadmap

### ISSUE THREAD

**Issue by kisasexypantera94** [kisasexypantera94/urukrama#2]
- [x] Vamana Algorithm
- [x] Batch Insert
- [x] Product Quantization
- [ ] Larger-than-RAM datasets
   - [x] On-Disk Clusterization
   - [ ] Demo (too lazy for now)
- [x] mmap
   - [x] Linux
   - [x] MacOS
   - [x] Windows
- [ ] madvise
- [ ] Beam search with mmap
- [ ] Direct I/O 
   - [ ] Linux
   - [ ] MacOS
- [ ] Manual caching with Direct I/O
- [ ] Beam search with Direct I/O
- [ ] Filtered-DiskANN
- [ ] Fresh-DiskANN
